### ISSUE TITLE
[unreal] Crowd management: peds & cars (basic)

### ISSUE THREAD

**Issue by JehanneDussert** [twin-city/unreal-project#24]
- [x] Recherches
- [x] Premiers tests
- [x] Implémentation simple sur TwinCity
- [x] Zone shape peds à la main
- [x] Zone shape vehicles à la main
- [x] Fix hair of the characters
- [x] Fix DA_Crowd du Mass Entity Config Asset

**Comment by JehanneDussert** [comment]
@remisansfamine à faire si possible semaine du 19/12

**Comment by notraore** [comment]
Tutotial intersection Pietons : https://www.youtube.com/watch?v=D74LyaIiik8

**Comment by JehanneDussert** [comment]
La piste Houdini a été abandonnée, nous basculons sur une map réalisée sur Blender
